language: python
python:
  - 2.7
  #- 3.2  # Flask does not seem to support Python3
install: pip install -r requirements/test.txt
script:
    # ensure the github host SSL certificate will be accepted when cloning dummyrepo:
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - ./scripts/test
